[[pages]]
path = "project_1/Hello.py"
name = "Главная страница"
icon = "🏠"

[[pages]]
path = "project_1/pages/1_tariff_recommendation.py"
name = "Рекомендация тарифа"
icon = ":receipt:"

[[pages]]
path = "project_1/pages/2_clients_churn.py"
name = "Отток клиентов «Бета-Банка»"
icon = ":classical_building:"

[[pages]]
path = "project_1/pages/3_booking_cancel_pred.py"
name = "Прогнозирование оттока клиентов в сети отелей «Как в гостях»"
icon = ":house_buildings:"

[[pages]]
path = "project_1/pages/4_toxic_comments.py"
name = "Выявление негативных комментариев с BERT"
icon = ":female-student:"

[[pages]]
path = "project_1/pages/5_star_temperature.py"
name = "Прогнозирование температуры звезды"
icon = ":star:"

[[pages]]
path = "project_1/pages/6_sql_stackoverflow.py"
name = "Анализ данных StackOverflow"
icon = ":page_facing_up:"

[[pages]]
path = "project_1/pages/7_car_cost_pred.py"
name = "Определение стоимости автомобилей"
icon = ":car:"

[[pages]]
path = "project_1/pages/8_accident_prediction.py"
name = "Разработка модели для оценки ДТП"
icon = ":rotating_light:"

[[pages]]
path = "project_1/pages/9_taxi_orders_prediction.py"
name = "Прогнозирование заказов такси"
icon = ":taxi:"

[[pages]]
path = "project_1/pages/10_power_forecasting.py"
name = "Потребление электроэнергии производством"
icon = ":factory:"